Print a message when the CSS check fails

diff --git a/bin/check-compiled-css b/bin/check-compiled-css
--- a/bin/check-compiled-css
+++ b/bin/check-compiled-css
@@ -3,4 +3,7 @@
 set -euo pipefail # exit on any error, don't allow undefined variables, pipes don't swallow errors
 
 # Check that a 'visibility:' CSS rule is present in the compiled CSS.
-grep -q 'visibility:' output/_bridgetown/static/index.*.css
+if ! grep -q 'visibility:' output/_bridgetown/static/index.*.css ; then
+  echo "ERROR: No 'visibility:' CSS rule found in compiled CSS."
+  exit 1
+fi
